In [37]:
# Before we begin, let's load the libraries.
%pylab notebook
import numpy as np
import numpy.linalg as la
from readonly.PageRankFunctions import *
np.set_printoptions(suppress=True)

Populating the interactive namespace from numpy and matplotlib


In [38]:
# Replace the ??? here with the probability of clicking a link to each website when leaving Website F (FaceSpace).
L = np.array([[0,   1/2, 1/3, 0, 0,   0 ],
              [1/3, 0,   0,   0, 1/2, 0 ],
              [1/3, 1/2, 0,   1, 0,   1/2 ],
              [1/3, 0,   1/3, 0, 1/2, 1/2 ],
              [0,   0,   0,   0, 0,   0 ],
              [0,   0,   1/3, 0, 0,   0 ]])

In [39]:
eVals, eVecs = la.eig(L) # Gets the eigenvalues and vectors
order = np.absolute(eVals).argsort()[::-1] # Orders them by their eigenvalues
eVals = eVals[order]
eVecs = eVecs[:,order]

r = eVecs[:, 0] # Sets r to be the principal eigenvector
100 * np.real(r / np.sum(r))

array([16.        ,  5.33333333, 40.        , 25.33333333,  0.        ,
       13.33333333])

In [52]:
a =np.array(np.arange(1,11))
np.absolute(a).argsort()[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [58]:
r = 100*np.ones(6)/6

In [59]:
L @ r

array([13.88888889, 13.88888889, 38.88888889, 27.77777778,  0.        ,
        5.55555556])

In [63]:
r = 100 * np.ones(6) / 6 # Sets up this vector (6 entries of 1/6 × 100 each)
for i in np.arange(10000) : # Repeat 100 times
    r = L @ r
r

array([16.        ,  5.33333333, 40.        , 25.33333333,  0.        ,
       13.33333333])

In [66]:
M = np.array([[4, -5, 6],
              [7, -8, 6],
              [3/2, -1/2, -2]])
vals, vecs = np.linalg.eig(M)
vecs

array([[-0.6882472 , -0.66666667,  0.40824829],
       [-0.6882472 , -0.66666667, -0.40824829],
       [-0.22941573,  0.33333333, -0.81649658]])

In [77]:
N = np.array([[0,0,0,1],[1,0,0,0],[0,1,0,0],[0,0,1,0]])
(np.linalg.eig(N)[1])

array([[-0.5+0.j ,  0. -0.5j,  0. +0.5j, -0.5+0.j ],
       [ 0.5+0.j , -0.5+0.j , -0.5-0.j , -0.5+0.j ],
       [-0.5+0.j , -0. +0.5j, -0. -0.5j, -0.5+0.j ],
       [ 0.5+0.j ,  0.5+0.j ,  0.5-0.j , -0.5+0.j ]])

In [71]:
np.real(np.linalg.eig(N)[0])

array([-1.,  0.,  0.,  1.])

In [72]:
P = np.array([[0.1,.1,.1,.7],[.7,.1,.1,.1],[.1,.7,.1,.1],[.1,.1,.7,.1]])
np.linalg.eig(P)[0]

array([ 1. +0.j , -0.6+0.j , -0. +0.6j, -0. -0.6j])

In [80]:
(np.linalg.eig(P)[1])

array([[ 0.5+0.j ,  0.5+0.j ,  0.5+0.j ,  0.5-0.j ],
       [ 0.5+0.j , -0.5+0.j ,  0. -0.5j,  0. +0.5j],
       [ 0.5+0.j ,  0.5+0.j , -0.5+0.j , -0.5-0.j ],
       [ 0.5+0.j , -0.5+0.j , -0. +0.5j, -0. -0.5j]])

In [78]:
N

array([[0, 0, 0, 1],
       [1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0]])

In [79]:
np.linalg.eig(N)

(array([-1.+0.j,  0.+1.j,  0.-1.j,  1.+0.j]),
 array([[-0.5+0.j ,  0. -0.5j,  0. +0.5j, -0.5+0.j ],
        [ 0.5+0.j , -0.5+0.j , -0.5-0.j , -0.5+0.j ],
        [-0.5+0.j , -0. +0.5j, -0. -0.5j, -0.5+0.j ],
        [ 0.5+0.j ,  0.5+0.j ,  0.5-0.j , -0.5+0.j ]]))

In [81]:
np.linalg.eig(P)

(array([ 1. +0.j , -0.6+0.j , -0. +0.6j, -0. -0.6j]),
 array([[ 0.5+0.j ,  0.5+0.j ,  0.5+0.j ,  0.5-0.j ],
        [ 0.5+0.j , -0.5+0.j ,  0. -0.5j,  0. +0.5j],
        [ 0.5+0.j ,  0.5+0.j , -0.5+0.j , -0.5-0.j ],
        [ 0.5+0.j , -0.5+0.j , -0. +0.5j, -0. -0.5j]]))